name: ci-golang-workflow
on: 
  pull_requests:
      branches: 
        - develop
        
jobs:
    check-application:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: 1.15
        - run: go test
        - run: go run math.go    
docker run -d \
  -p 3000:3000 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/gitness:/data \
  --name gitness \
  --restart always \
  harness/gitness